[workspace]
release_always = false
changelog_update = false
dependencies_update = false
git_release_enable = false
git_tag_enable = false
publish = false
semver_check = false

[[package]]
name = "domyjob"
changelog_path = "./CHANGELOG.md"
changelog_update = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
version_group = "domyjob"

[[package]]
name = "domyjob-core"
version_group = "domyjob"

[[package]]
name = "xtask"
release = false

[changelog]
protect_breaking_commits = true
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
