[package]
name = "domyjob-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
domyjob = { path = "../crates/domyjob" }
serde_json = "1"
xtask = { path = "../xtask" }

[workspace]

[[bin]]
name = "requests"
path = "fuzz_targets/requests.rs"
test = false
doc = false
bench = false

[[bin]]
name = "orders"
path = "fuzz_targets/orders.rs"
test = false
doc = false
bench = false

[[bin]]
name = "releases"
path = "fuzz_targets/releases.rs"
test = false
doc = false
bench = false

[[bin]]
name = "terminal"
path = "fuzz_targets/terminal.rs"
test = false
doc = false
bench = false
